# syntax=docker/dockerfile:1

ARG NODE_VERSION=18.19.0

################################################################################
# Use node image for base image for all stages.
FROM node:$NODE_VERSION-alpine AS base
WORKDIR /app

FROM base AS dev
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --include=dev

EXPOSE 9000

COPY . .

FROM base AS prod
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev
COPY . .
